import { Inter } from 'next/font/google'
import './globals.css'
import Provider from './Provider'
import ThemeButton from './components/ThemeButton'
import Link from 'next/link'
import Navbar from './Navbar'
import WelcomePage from './components/Welcome'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SUMMARIZER | Al Amin Muhammad | ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <Provider>
         
          <Navbar />
          {/* <header className='py-6 dark:bg-gray-900'>
            <nav className='container flex items-center justify-between'>
              <ul className='flex gap-6'>
                <li>
                  <Link href='/'>Home</Link>
                </li>
                <li>
                  <Link href='/summarizer'>Summarizer</Link>
                </li>
              </ul>
              <ThemeButton />
            </nav>

          </header> */}
          <main className="app">
           <WelcomePage/>
          </main>
          <footer className="flex justify-center items-center h-16 dark:bg-background dark:text-green-400">
            <h1 className="dark:bg-background hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Powered By Al Amin Muhammad</h1>
          </footer>
        </Provider>
      </body>
    </html>
  )
}
